// Importing required components and styles
import Footer from '@/components/Footer/Footer';             // Footer component
import Header from '@/components/Header/Header';             // Header component
import "./globals.css";                                       // Global styles

import { Inter } from 'next/font/google';                    // Importing Inter font from Google Fonts
import "../assets/css/fontawesome.min.css";                  // FontAwesome CSS

// Define Inter font with Latin subset
const inter = Inter({ subsets: ['latin'] });

// Metadata for the application
export const metadata = {
  title: 'USA Website Design',                               // Website title
  description: 'Generated by create next-app Developed by 3rudit3',  // Website description
}

/**
 * Root Layout component
 * 
 * This component represents the root layout structure of the application.
 * It includes the following sections:
 * - Header: Top navigation and branding of the website
 * - children: Main content of the specific page being rendered
 * - Footer: Bottom section containing footer information
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
